package org.example;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.eid
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_name
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_telecom
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    private String empTelecom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.did
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    private Integer did;

    public Emp() {
    }

    public Emp(Integer eid, String empName, String empTelecom, Integer did) {
        this.eid = eid;
        this.empName = empName;
        this.empTelecom = empTelecom;
        this.did = did;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "eid=" + eid +
                ", empName='" + empName + '\'' +
                ", empTelecom='" + empTelecom + '\'' +
                ", did=" + did +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.eid
     *
     * @return the value of emp.eid
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.eid
     *
     * @param eid the value for emp.eid
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_name
     *
     * @return the value of emp.emp_name
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_name
     *
     * @param empName the value for emp.emp_name
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_telecom
     *
     * @return the value of emp.emp_telecom
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public String getEmpTelecom() {
        return empTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_telecom
     *
     * @param empTelecom the value for emp.emp_telecom
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public void setEmpTelecom(String empTelecom) {
        this.empTelecom = empTelecom == null ? null : empTelecom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.did
     *
     * @return the value of emp.did
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.did
     *
     * @param did the value for emp.did
     *
     * @mbg.generated Fri Mar 13 17:42:26 HKT 2026
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}